version: "3"

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - 8888:8888
    networks:
      - default

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 8787:8787
    networks:
      - default
    stop_grace_period: 1s

networks:
  default:
    driver: bridge
