version: '3'
services:
  go-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8888"
  
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true